# Generated by Django 4.2.30 on 2026-05-04 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('date', models.DateField(db_index=True)),
                ('ai_categories', models.JSONField(blank=True, help_text='e.g. ["Health", "Work"]', null=True)),
                ('mood_score', models.IntegerField(blank=True, help_text='1 (very low) to 5 (very high), inferred by AI from entry tone', null=True)),
                ('mood_arc', models.CharField(blank=True, choices=[('improving', 'Improving'), ('declining', 'Declining'), ('flat', 'Flat'), ('stable', 'Stable')], help_text='How the mood shifts within a single entry', max_length=20, null=True)),
                ('habits_detected', models.JSONField(blank=True, null=True)),
                ('people_mentioned', models.JSONField(blank=True, help_text='e.g. ["Alice", "Bob"]', null=True)),
                ('pattern_insight', models.TextField(blank=True, help_text='One AI-generated observation specific to this entry', null=True)),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='entry_user_date_idx')],
            },
        ),
    ]
